In [20]:
import torch
import os
inputs = torch.tensor([[[[1., 2.],
                         [3., 4.]]]])

inputs.shape


torch.Size([1, 1, 2, 2])

#Fully Connected Layers

In [21]:
fc = torch.nn.Linear(4, 2)

weights = torch.tensor([[1.1, 1.2, 1.3, 1.4],
                        [1.5, 1.6, 1.7, 1.8]])
bias = torch.tensor([1.9, 2.0])
fc.weight.data = weights
fc.bias.data = bias


In [22]:
#torch.relu(fc(inputs.view(-1, 4)))
fc(inputs.view(-1, 4))

tensor([[14.9000, 19.0000]], grad_fn=<AddmmBackward0>)

#Method 1: Convolutions with kernels equal to the input size

In [23]:
conv = torch.nn.Conv2d(in_channels=1,
                       out_channels=2,
                       kernel_size=inputs.squeeze(dim=(0)).squeeze(dim=(0)).size())
print(conv.weight.size())
print(conv.bias.size())

torch.Size([2, 1, 2, 2])
torch.Size([2])


In [24]:
conv.weight.data = weights.view(2, 1, 2, 2)
conv.bias.data = bias

In [25]:
torch.relu(conv(inputs))

tensor([[[[14.9000]],

         [[19.0000]]]], grad_fn=<ReluBackward0>)

#Methods 2: Convolution with 1x1 kernels

In [30]:
conv = torch.nn.Conv2d(in_channels=4,
                       out_channels=2,
                       kernel_size=(1, 1))

#conv.weight.data = weights.view(2, 4, 1, 1)
#conv.bias.data = bias
conv(inputs.view(1, 4, 1, 1))
#torch.relu(conv(inputs.view(1, 4, 1, 1)))
#torch.relu(conv(inputs))

tensor([[[[ 0.2102]],

         [[-0.2139]],

         [[ 1.3615]]]], grad_fn=<ThnnConv2DBackward0>)

In [27]:
m = torch.nn.Linear(2, 3)
input = torch.tensor([[1., 2.]])
output = m(input)
output
#print(output.size())




tensor([[-0.7626,  0.7270, -1.6125]], grad_fn=<AddmmBackward0>)

In [ ]:
os.path.dirname()